import mongoose from "mongoose";

const itemSchema = new mongoose.Schema(
  {
    img: { type: String },

    name: {
      type: String,
      required: true,
      trim: true,
      maxlength: 100,
    },

    // 🔥 IMPORTANT: for deduplication
    normalizedName: {
      type: String,
      lowercase: true,
      trim: true,
      index: true,
    },

    quantity: {
      type: String,
      default: "",
    },

    unit: {
      type: String, // optional (kg, pcs, etc.)
    },

    category: {
      type: String,
      enum: ["Vegetable", "Fruit", "Dairy", "Spices", "Bakery", "Other"],
      default: "Other",
    },

    status: {
      type: String,
      enum: ["pending", "purchased"],
      default: "pending",
      index: true,
    },

    estimatedPrice: {
      type: Number,
      default: 0,
    },

    // 🔥 AI Features
    aiGenerated: {
      type: Boolean,
      default: false,
    },

    priority: {
      type: String,
      enum: ["high", "medium", "low"],
      default: "medium",
    },

    alternatives: [String], // ["paneer instead of cheese"]

    addedFromRecipe: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Recipe",
      default: null,
    },
  },
  { timestamps: true }
);

const shoppingListSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true, // 🔥 PERFORMANCE
    },

    items: [itemSchema],

    autoGenerated: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);


export const ShoppingList = mongoose.model(
  "ShoppingList",
  shoppingListSchema
);