import mongoose from "mongoose";

const shoppingListSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  items: [
    {
      name: { type: String, required: true },  // "Tomato"
      quantity: { type: String },              // "2 pcs", "500g"
      category: { type: String },              // "Vegetable", "Dairy", etc.
      isPurchased: { type: Boolean, default: false }, // check/uncheck
      addedFromRecipe: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: "Recipe", 
        default: null 
      }, // traceable to a recipe
    },
  ],
  autoGenerated: { type: Boolean, default: false }, // true if created via recipe/AI
},{timestamps: true});

export const ShoppingList = mongoose.model("ShoppingList", shoppingListSchema);
